### ISSUE TITLE
"IntelligenceSupportToOperations.arpx" does not have tools in toolboxes with ArcGIS Pro 1.1

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1007]
Received IntelligenceSupportToOperations.arpx from @phil7277 and @conklinbd that they used with their trip to Colombia (week of 8/25 (ca.) The arpx file did not contain tools when they were expanded in the table of contents. 
![intelligencesupporttooperationstools](https://cloud.githubusercontent.com/assets/5074686/9933746/03169588-5d1b-11e5-8a05-8afbefe41dca.png)

-This was experienced with ArcGIS Pro version 1.1 (final).

Please check if tools get disseminated/ work with ArcGIS Pro version 1.1

**Comment by ScottCecilio** [comment]
@jfrygeo @conklinbd , I gave @phil7277  this demonstration in a .zip format before the Colombia trip because the project was failing to package.  I have recently discovered that the failure was being caused by some of the tools referencing a local geodatabase on the developers machine.  I have since extracted only the necessary tools from the toolboxes and was able to successfully package the deomonstration.  You can find and download the package here:

\\disldb\OpsServerStaging\2015_Q4\DemoAndScripts\Military\LandOperations

**Comment by conklinbd** [comment]
:+1:
