### ISSUE TITLE
Hosted service Illicit_Drug_Grows/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1049]
The hosted service "Illicit Drug Grows" item exists 99c9cd90af9a4a3c9c315b45edb02216 but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by conklinbd** [comment]
Based on the lack of activity on this item. I am going to delete the item at 1100 today. If you think this is in error please respond by then.  Items like this cause us problems in QA/QC and have the potential to cause other problems as individuals reuse this content in their demo's/presentations.

**Comment by elinz** [comment]
To the best of my knowledge this service is being referenced by the following resources:
- Web Map, a4c628fc4aa04a05ad30fd32613df340, "Illicit Drug Grows", Natalie F.
- Web Mapping Application, f6e165bf688c46daa06048fed1fb43e9, "Illicit Drug Grows",  Natalie F.
- Web Map, 889abe9dfb5a4c0e93920257652fb740, "Illicit Drug Grows Map", Phil S.
- Web Mapping Application, 77f7ad815fa3426c886d7b03fe23b328, "Illicit Drug Grows (Summary Application)", Phil S.

**Comment by conklinbd** [comment]
Based on the fact that this is not used in any released content. @phil7277 and @nfeuerstein will need to fix their own web maps.

**Comment by conklinbd** [comment]
@elinz to verify.

**Comment by nfeuerstein** [comment]
Web Map, a4c628fc4aa04a05ad30fd32613df340, "Illicit Drug Grows", Natalie F.
Web Mapping Application, f6e165bf688c46daa06048fed1fb43e9, "Illicit Drug Grows", Natalie F.

@conklinbd @elinz the two items above (web map and web app) are in the release/review group and have been.  They are "ready" for release and should be released.  The problem happened because the workflow, to drag and drop a CSV and utilize smart mapping to make a map and then publish an app creates the "unsupported" hosted feature service and (to the best of my knowledge) its not easy to tell from the item if its a "supported" hosted service or an "unsupported" hosted service.

I can republish the data as a "supported" service to have the examples, or we can just publish the csv and people can follow the same workflow to create their own web map and web app in a few easy clicks.

**Comment by elinz** [comment]
@conklinbd Please advise course of action @nfeuerstein should take based on her last comments.

**Comment by nfeuerstein** [comment]
@conklinbd @elinz - I republished the drug grow feature service (the legit way) and updated the web map (the ones owned by me, not the ones owned by @phil7277.  They are all shared with the release review group.

**Comment by elinz** [comment]
NOTE: Republished service name changed from Illicit_Drug_Grows to DrugGrows.

Verified that a service definition item now exists for this new service. Closing issue.
