### ISSUE TITLE
Released web map "ISR Mission Reports" references demo service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1080]
@ScottCecilio Web map "ISR Mission Reports" id d1d694ff35d34f29b1b16b54a72e0e4f is released (owned by ReleasedIntel, however, this web map references a feature service "Mission Report (Feature Layer)" id d78f22ee0b5e454588b9a0883cfd8d22 which is only being released as a demo item (i.e. this item is shared with the "Demo Review" group).

All services referenced by a released web map should also be released...i.e. ultimately owned by one of the "Released" owners. It should not be released as demo content.

@lfunkhouser FYI.

**Comment by lfunkhouser** [comment]
@elinz @ScottCecilio @jrweakland I've changed the owner of Web map "ISR Mission Reports" id d1d694ff35d34f29b1b16b54a72e0e4f to DemoMilitary since 1)it is a Military item not Intel, 2) "Mission Report (Feature Layer)" id d78f22ee0b5e454588b9a0883cfd8d22 is used for the Land Ops demo and wasn't intended on being released at this time.

**Comment by elinz** [comment]
Verified issue was fixed by ownership of item changing to "DemoMilitary". Closing issue.
