### ISSUE TITLE
Feature layer with ~50,000 features publishes with 0 features

### ISSUE THREAD

**Issue by DeborahRoth** [Esri/ops-server-config#1152]
@conklinbd 
A feature layer with ~50,000 features successfully published from ArcMap to the Ops Server, however it came over as an empty feature layer with a blank attribute table and no features. It successfully published as a map service using nsec.esri.com.

The offending data and associated mxd are saved here:
\\mrhyde\public\Jess\OPSServer\ *TaxParcelQuery.zip*

FYI: @jessnoo

**Comment by conklinbd** [comment]
@DeborahRoth and @jessnoo. My impression is that this is caused by the uppercase/lowercase issue as well. The Map Service works because the data is kept in FGDB so there is no change to the data during the publishing process. 

I can't access the mrhyde location currently to try to correct the field name issue.

Based on the large # of records in the service, I am thinking it might be better to first copy the data to a registered data store on the server prior to publishing. We will need to create a new EGDB for you to use. I will need to coordinate this with @elinz and see if this will cause any problems.

**Comment by conklinbd** [comment]
The EGDB has been created. Please try the approach of copying the data to the EGDB first and then publishing using that as your data source.

**Comment by conklinbd** [comment]
Based on email with @DeborahRoth the Map Service Publishing is sufficient for her needs so we will release it this way.
