### ISSUE TITLE
Layer ids have changed after republishing MonterreyAirportCompoundMap_WFL feature service, modify all web maps

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1170]
The MonterreyAirportCompoundMap_WFL feature service no longer has a layer id 6. It has only the layers below; I believe what was layer id 6 is now id 5.

![image](https://cloud.githubusercontent.com/assets/4635490/10293325/ba932978-6b68-11e5-89ed-0cf73e3c5b23.png)

The web maps that references this feature service are:
- [x] e9afca99ffa14bf0b064df6631210f60, "Monterey Airport (Overview)", owner=DemoMilitary
- [x] b83cf730926943bdab17b0b91e9d6d98, "Monterey Region (Incident Analysis)", owner=DemoMilitary

**Comment by ScottCecilio** [comment]
I am not sure what you are look for here?

**Comment by conklinbd** [comment]
@ScottCecilio you will need to replace the layers in these web maps with the layers from this service. I can just do this for you if you want since both web maps have been released. 

If you want me to do it let me know. I will also need to know if you modified the symbology or popup info for these services when you added them to the web map.

**Comment by ScottCecilio** [comment]
@elinz @conklinbd I believe that this is not complete.  Please verify and close.

**Comment by conklinbd** [comment]
Verified: e9afca99ffa14bf0b064df6631210f60 uses layers 0-4 which seems correct
b83cf730926943bdab17b0b91e9d6d98 uses layer 5 which is the airfield,

**Comment by conklinbd** [comment]
@lfunkhouser I changed these back to DemoMilitary user.
