### ISSUE TITLE
Add time delay between publishing calls in PublishToOpsServer.py

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#125]
Occasionally we have receive 99999 errors when publishing .sd files. Rerunning script successfully publishes the service. I don't know if this is a resource conflict issue or not, but want to add to time delay within publishing "loop" to see if this helps.

**Comment by VytautasGipiskis** [comment]
I had an issue when publishing a services. MGRS.SD failed to publish with error below, while others published without issues. I think this issue was caused because of security alert box - while I pressed OK button immediately, it probably took some time for the system to get the approval.
As a side note - i republished it manually, but struggled to find a ArcGIS Server folder name to use it. Would be great to have sort of document where each service have to be placed.
  
- Service Definition: F:\Ops\OPSServerInstall\Server\ServiceDefinitions\i009d56e5-aa00-4cf7-81f9-bc86eb8eb075\MGRS.sd (1 of 120)...
        Owners: ['OpsServer']
        Groups: ['avel5840@AVWORLD:Test Review']
        Publish service? True

        **********************************************
        *ERROR encountered:
        Error Info:
        ERROR 999999: Error executing function.
Failed to connect() to host or proxy.
Failed to execute (UploadServiceDefinition).
