### ISSUE TITLE
Visibility and Range item is for 10.2

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1269]
@dfoll @nfeuerstein @joebayles 
The portal item for Visibility and Range is for 10.2. The most recent version on the download site is 10.3
If you want a document link created for this item for this Ops Server release, please update the portal item with the correct information 
If you do not want a document link for this item, please unshare the item with Release Review until the changes to the portal item are made and then it can be released by TemplateIntelligence

**Comment by conklinbd** [comment]
If this isn't resolved by 1300 this item will not be released with the Ops Server.

**Comment by dfoll** [comment]
i will take the 103 version from the download site and use it to update the portal item

**Comment by dfoll** [comment]
replaced with the version from the downloads page.... NOTE... a new portal item was created because the file associated with the old portal item had "3.0.0" appended to the file name... this was incorrect and prohibited me from updating that portal item. i have shared with release review, and enabled delete protection, but @lfunkhouser @nfeuerstein  i cannot switch owner to natalie so that it gets picked up by the release team.

**Comment by lfunkhouser** [comment]
verified as fixed. Released by TemplateMilitary
