### ISSUE TITLE
ArcGIS for Geospatially Enabling the Intelligence Collector (Map Journal) Depends on Unreleased content

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1275]
This is a serious issue. There is numerous sets of content which is not released for this app. 

in Demo review
- [x] id:d6f09cebdbad474a8c6cad9e94609222 ISR Mission Report Dashboard (Single Display)

In Intel QA/QC
- [x] id:0e32cae8e76c47eb9013fd5123287897 Question 1- Geospatially Enabling the Intelligence Collector
- [x] id:b480e023c02947a2b5790d476cbf1b7d Question 3- Geospatially Enabling the Intelligence Collector
- [x] id:f8cb7a4ac0af40de9f5d7b69cc6f6145 Illicit Drug Grows (Web-App Builder)
- [x] id:386f8a3d1f9e4629b63fc4023ba78ead/data Question 4- Geospatially Enabling the Intelligence Collector

Not in Review
- [x] id:889abe9dfb5a4c0e93920257652fb740 Illicit Drug Grows Map owned by @phil7277  
- [x] id:77f7ad815fa3426c886d7b03fe23b328 Illicit Drug Grows (Summary Application) owned by @phil7277  

@phil7277 @nfeuerstein @ScottCecilio I hope somebody was already working on this.

**Comment by nfeuerstein** [comment]
I fixed/sent to release what I could.  The following still have issues:
[ ] id:f8cb7a4ac0af40de9f5d7b69cc6f6145 Illicit Drug Grows (Web-App Builder) - there are no operational layers.
[ ] id:386f8a3d1f9e4629b63fc4023ba78ead/data Question 4- Geospatially Enabling the Intelligence Collector - there are no image permissions noted.

We've already released an Illicit Drug Grows Map (a4c628fc4aa04a05ad30fd32613df340) and an Illicit Drug Grows Summary App (f6e165bf688c46daa06048fed1fb43e9).  Can we use those instead of releasing duplicates?

@conklinbd @phil7277

**Comment by conklinbd** [comment]
@nfeuerstein is going to fix this.

**Comment by nfeuerstein** [comment]
-[  ] id:0e32cae8e76c47eb9013fd5123287897 Question 1- Geospatially Enabling the Intelligence Collector - shared with Demo Review Group
 -[  ] id:b480e023c02947a2b5790d476cbf1b7d Question 3- Geospatially Enabling the Intelligence Collector - shared with Demo Review Group
-[  ] id:f8cb7a4ac0af40de9f5d7b69cc6f6145 Illicit Drug Grows (Web-App Builder) - replaced illicit drug grow feature service with a present/working service
-[  ] id:386f8a3d1f9e4629b63fc4023ba78ead/data Question 4- Geospatially Enabling the Intelligence Collector - deleted this item because there were lots of pictures without credits and replaced the main stage in the Map Journal with a URL to the Map Journal app template item.

Also, replaced Illicit Drug Grows Map and Summary App with the already released items rather than duplicates.

**Comment by conklinbd** [comment]
I would like to verify this one.

**Comment by conklinbd** [comment]
This content is not released and wasn't shared to demo review group. I shared to demo review.

- [ ] id:0e32cae8e76c47eb9013fd5123287897 Question 1- Geospatially Enabling the Intelligence Collector
- [ ] id:f199cc8b220e464c930a7a2e706625de Question 2- Geospatially Enabling the Intelligence Collector
- [ ] id:b480e023c02947a2b5790d476cbf1b7d Question 3- Geospatially Enabling the Intelligence Collector

These are all pictures.

**Comment by conklinbd** [comment]
@lfunkhouser to release the remaining items.

**Comment by conklinbd** [comment]
Verified content released.
