### ISSUE TITLE
TEM2015 Test 02:  There are two versions of the Coastal Relief Model

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1323]
There are two versions of the Coastal Relief Model.  One is owned by ReleasedIntel and the other is owned by admin.  The ReleasedIntel points to the develeopment server while the admin service points to the Test server.  
To reproduce search for Coast Relief.

![image](https://cloud.githubusercontent.com/assets/5116835/10498194/3242cdc6-727f-11e5-8aed-e142c2c6a135.png)

**Comment by elinz** [comment]
The portal item owned by "admin" is the publisher of the service on the test ArcGIS Server. The portal item owned by ReleasedIntelligence is the owner of the service on the dev ArcGIS Server. The RemapIDsOnServices.py script should modify the guid stored in the service json so that the service is remapped to the original owner. The fact that the ReleasedIntelligence item still references the dev server url should explain the issue #1298. At this point I'm not sure why the url of this item references the dev server because the server name on other portal service items were modified to reference the test server.

**Comment by elinz** [comment]
@NatalieCampos @conklinbd I'll manually edit the service json to point to the item owned by "ReleasedIntelligence" and delete the item owned by "admin".

**Comment by elinz** [comment]
@NatalieCampos @conklinbd Finished the modifications as well as editing the URL on the portal item. Assigning back to verify

**Comment by NatalieCampos** [comment]
The fix has been verified.
