### ISSUE TITLE
TEM2015 Test 02: Mission Report geoform missing coded value domains

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1332]
Mission Report from Aerial Assets for use with Land Operations geoform id:b2838eb9eddb434bb77738825640ea4c

Report Classification and Platform Type fields should have a drop-down using coded-value domains.  Is it possible something happened with the copy that only the field marked "required" kept the coded value domains?

![image](https://cloud.githubusercontent.com/assets/3800729/10516451/31fadece-730d-11e5-9ce0-db3eba176a3c.png)

**Comment by conklinbd** [comment]
I will look into this as soon as dev server is back up.

**Comment by conklinbd** [comment]
The behavior of this application is the same on the development server as it was on the nsec server so this error was not introduced during the copying process. 

On the development server this form relies on this service id:b1ab24b97f9f4bd4925d2a5f0b792fce
Military/IntelReports/FeatureServer/0. This service does not have coded value domains.
The only reason there are drop downs for mission type is because this field is tied to the symbology for the service (hence the required tag). 

This looks like a regression from the fixing of #1195.

@phil7277 or @ScottCecilio We need assistance fixing this issue. I need the original documents and Geodatabases for these services. If we don't get this by 1300 PST we can not resolve this issue for the release.

**Comment by conklinbd** [comment]
We will see if we can find anything. @jrweakland or @topowright

**Comment by conklinbd** [comment]
We are trying to replace this service:
id:b1ab24b97f9f4bd4925d2a5f0b792fce

**Comment by jrweakland** [comment]
@conklinbd - @topowright is sending you a mpk from @phil7277 that was used for install at the usmc prototype lab.

**Comment by conklinbd** [comment]
This is still for @topowright to work with @elinz

**Comment by topowright** [comment]
@conklinbd @jrweakland Added the following domains to the SDE: 

MIssion Type
Classification
Platform Type
Sensor Capabilities

Added new features using the Geoform.

**Comment by topowright** [comment]
@lfunkhouser Please verify

**Comment by lfunkhouser** [comment]
verified as fixed on test server
