### ISSUE TITLE
TEM2015 Test 02: Layers do not draw in Maritime Weather Environment and Operational Effects Application

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1343]
Only one layer currently draws in the application: 5b1b0859e54c47cc9a6dd8d3ab288575

I think this problem is because there is no time widget loaded in the map. Layers that are missing: 

Wind Warnings
Wave Warnings
Beaufort Sea States
Underway Replenishment
Winds HIllshade

**Comment by conklinbd** [comment]
@topowright the issue seems to actually be that the is no service Military/WaveWatchIII. When the server is back up I will see if this item was released. 
@jfrygeo

**Comment by conklinbd** [comment]
The title of the app is Maritime Weather Environment and Operational Effects

**Comment by elinz** [comment]
@topowright @conklinbd @jfrygeo service ags/admin/services/Military/WaveWatchIII.ImageServer does exist on test server so it was released.

**Comment by topowright** [comment]
@conklinbd @jfrygeo 
This is the item I have created for that issue: 

https://github.com/Esri/ops-server-config/issues/1345

**Comment by conklinbd** [comment]
This works now. I think this is strictly a performance issue.

**Comment by topowright** [comment]
@conklinbd I still do not see layers drawing in the application

**Comment by conklinbd** [comment]
Wait a few minutes and then try again. 
@topowright

**Comment by jfrygeo** [comment]
For the WebApp, "Maritime Weather Environment"  (f844541853f743f7a7c6f1b13aa680a8), there's a performance issue/widget issue with the version of Web AppBuilder deployed with this OpsServer.

 In order to make the layers load quickly, press on the time widget, if the time widget is not turned on, it takes a few minutes for the layers to load. This issue has been fixed in new versions of the Web AppBuilder as you can choose to have controls open the widgets when the application is loaded. This was logged as:

[ENH-000088947 Enhancement Request: Allow the time slider widget for the web AppBuilder to be available as an on-panel widget which can be opened at the start.] on 7/9/15.

**Comment by conklinbd** [comment]
I am going to treat this as a known issue for 10.3.1. We can retest with 10.4
