### ISSUE TITLE
TEM2015 Test 02:  No damage assessment features display on map

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1349]
Testing What is Web GIS web mapping Application, item 42b2b67c672045388433bacd6e2a6676
Operational Data, slide 2, Field Data Tsunami Damage Assessment
No damage assessment features display on map; just basemap.
possibly related to https://github.com/Esri/ops-server-config/issues/1322
![image](https://cloud.githubusercontent.com/assets/3801392/10529302/8b433d02-7351-11e5-9ea5-eb2e818cd4c4.png)

**Comment by elinz** [comment]
The reason why features are not displayed is that the underlying feature service (Hosted/DamageAssessment/FeatureServer) contains no features. I checked on the dev server and this service is supposed to have features. This is a hosted service, which means it is republished to Ops Server through the service definition stored on the portal. I extracted the contents and examined the file geodatabase in the .sd and it contains no features. Which means the features were added to the dev service after it was published. If a hosted service requires features, these features must exist at the time of original publication.

**Comment by elinz** [comment]
I looked into this further. The web map associated with this app is referencing the service Hosted/DamageAssessment/FeatureServer. Examining the description on portal service item for this service states. "You can create an empty hosted feature service from this existing feature service." Therefore it was the intent of the service author that this service was not suppose it have any features. My assumption is that the author of this web map incorrectly choose to add the Hosted/DamageAssessment/FeatureServer instead of possibly the NationalIntelligence/DamageAssessment service. Remove "Showstopper" label.

**Comment by elinz** [comment]
I'll go ahead and extract the features from the service on dev server and load them into the file geodatabase in the .sd file. Assigning issue to me.

**Comment by elinz** [comment]
Replaced the DamageAssessment.sd in the build folder 20151011_0757\OPSServerInstall\Portal\PortalContent\ReleasedIntelligence\items\8b48ede2cfaa4252bc0ed2adb003e2a9\data.

NOTE: the the buildings and areas features classes have data. The bridge feature class didn't have any features in the dev server service.

**Comment by elinz** [comment]
Will verify on TEM2015 Test 03 server.

**Comment by elinz** [comment]
Verified on TEM2015 Test 03 server. Closing issue:
![image](https://cloud.githubusercontent.com/assets/4635490/10562368/be2d05fa-750d-11e5-8fe6-5ca9f8873286.png)
