### ISSUE TITLE
Unable to Add Domains to existing feature class  on SDE. 

### ISSUE THREAD

**Issue by phil7277** [Esri/ops-server-config#1394]
I would like to use the existing Domains to drive the types of information collected. The Domains I would like to use are:
Classification
SensorCapabilities
MissionTypes
PlatformTypes

**Comment by elinz** [comment]
Which SDE database are these domains associated with?

-------- Original message --------
From: Phil Suarez
Date:02/08/2016 12:56 PM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: [ops-server-config] Unable to Add Domains to existing feature class on SDE. (#1394)


I would like to use the existing Domains to drive the types of information collected. The Domains I would like to use are:
Classification
SensorCapabilities
MissionTypes
PlatformTypes

**Comment by elinz** [comment]
And which feature class?

-------- Original message --------
From: Phil Suarez
Date:02/08/2016 12:56 PM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: [ops-server-config] Unable to Add Domains to existing feature class on SDE. (#1394)


I would like to use the existing Domains to drive the types of information collected. The Domains I would like to use are:
Classification
SensorCapabilities
MissionTypes
PlatformTypes

**Comment by phil7277** [comment]
It is the “military.sde.missionreports” feature class. The Military.SDE does not have the coded value Domains.  This must have been recreated by someone when released. The original feature class that powered the apps was “currentoperations.sde. ISRMissionReports”. The CurrentOperations.SDE does have the coded values but is not used to support the feature services for this information layer.


Regards,
Phil

Phil Suarez | Solutions
Esri | Defense & Intelligence
8615 Westwood Center Dr. | Vienna, VA. 22180 | USA
T 909-793-2853<tel:909-793-2853> x2829 | M 571-328-6802<tel:571-328-6802>
psuarez@esri.com<mailto:psuarez@esri.com> | www.esri.com<http://www.esri.com/>

**Comment by elinz** [comment]
@phil7277 You can't make changes to the database schema because there are schema locks. The following list the services which are reference data from the military SDE database:
- Military/IntelReports (MapService: 60d9c717ebd64314bb1764bd5ea5c96b; FeatureService: b1ab24b97f9f4bd4925d2a5f0b792fce; both owned by DemoMilitary)
- Military/VehicleTrackRoutes (MapService: abe1a564e7df47a3a56461d25d2b467e; FeatureService: d92efeb3ca9147f9a7da1256a0c20b25; both owned by Patrick H.)
- Test/TestOOB (MapService: e7a517ab0d584b73aeb10db927ed82cc; FeatureService: a4cb99a97680430a940ce4473b583c2a; both owned by Patrick H.)

Coordinate with all users involved when these services can be stopped and I will stop them. You will then be able to add these domains to the the military database and assign to fields in the feature class. Assigned issue back to you.

**Comment by joebayles** [comment]
@topowright did you assume this issue as well?

**Comment by topowright** [comment]
This has been fixed and verified by @Dbarnes1
