### ISSUE TITLE
NationalIntelligence\Elevation service - appears to be using feet and meters for elevation surfaces

### ISSUE THREAD

**Issue by pshowalter** [Esri/ops-server-config#1410]
The NationalIntelligence\Elevation service MDS appears to be using a mix of data that includes data with elevation in feet, and meters. 

![image](https://cloud.githubusercontent.com/assets/6842145/13746651/acac7496-e9ca-11e5-876b-99b2c0b5f389.png)
![image](https://cloud.githubusercontent.com/assets/6842145/13746663/bb2a55c4-e9ca-11e5-87fd-5eeeacd11229.png)

**Comment by NatalieCampos** [comment]
@elinz This is an issue that has been repeatedly fixed.  There seems to be an issue with the mosaic datasets losing raster functions after they are 
1. republished as seen at last years UC both at UC and when we returned
2. there is a system upgrade 10.4

This issue should be investigated further so that the issue can be addressed without having a ton or fixes after items 1 or 2 are performed.

**Comment by NatalieCampos** [comment]
This service is for the Predicitive Analysis demo data.  Whoever built the 
\\[severname]\Data\DerivedLayers\PredictiveAnalysis.gdb\Elevation mosaic dataset within the PredictiveAnalysis.gdb needs to add the unit conversion raster function to the lidar data only and then regenerate the overviews.  <-- Assigning to @dfoll 

Additionally, I question on why there is a DemoIntelligence elevation service that uses the same elevation data as the Cached Elevation Service or the WGS84 elevation service.  @dfoll If this service is necessary cool but if not and either of the other two elevation services would suffice the please delete this service to reduce confusion to our portal users.  @lfunkhouser What would the process be to delete or remove an already released service?

**Comment by NatalieCampos** [comment]
Currently the NationalIntelligence\Elevation is a single raster created from multiple rasters.  Because of this I am unable to add the unit conversion raster function to the data that is in the wrong measurement units.  This single raster needs to be created.  I have discussed this with @dfoll.
 
@pshowalter There is debate on this service.  If you need an elevation service right now, please use the Cached World Elevation Service or the World Elevation WGS84 Service.  If either of these two services do not fit your needs please let me know and I will create one that does.  


![image](https://cloud.githubusercontent.com/assets/5116835/13821395/a79cf170-eb5e-11e5-9d8f-551ba5f4b7d0.png)

![image](https://cloud.githubusercontent.com/assets/5116835/13821574/6f49a52e-eb5f-11e5-9c82-2fc74994bef2.png)

**Comment by pshowalter** [comment]
Looks like it would be a good service to use for analysis, rather than global, but have found a few services to test with.
Objective was to test different elevation surface types (Elevation Service, fGDB, MDS, dted) and various PCS’s using  Military Tools for ArcGIS.


·        Cached World Elevation – does not display in my ArcMap 10.3.1 or Pro 1.2 – suggestions?  This service is Web Mercator

·        World Elevation WGS84 does display, and can test with this.

**Comment by NatalieCampos** [comment]
- cached world elevation is a Lerc service that can not be used in Pro but can still be viewed dynamically in ArcMap.  Though I don't know for how much longer.  To view it in ArcMap r-click in the properties and check the Enable Cache View.  

![image](https://cloud.githubusercontent.com/assets/5116835/13828906/54f6aeac-eb81-11e5-91a0-3f0f31e2e035.png)


If you need mosaic datasets you can use the MDs for elevation in 

\\[ServerName]\Data\FoundationOverlays\Elevation\MosaicDatasets

Anything just let me know.

**Comment by pshowalter** [comment]
If it’s going away, it may not be worth the effort to run to ground.

Enable Cache mode is checked, but nothing displays.
When I add the Service, I get an RGB Layer in the TOC, and it is just named “Cached World Elevation” not “NationalIntelligence\CachedWorldElevation” like I see in the TOC from your screen capture.
Also, Description should be changed if its not viewable in Pro

Description: A global multi-resolution Digital Terrain Model (DTM) to be used as a cached elevation surface in ArcGIS Pro or ArcGIS Scene Viewer. The World Elevation Cache service can only be viewed dynamically in ArcGIS Pro or ArcMap, and is not viewable in ArcGIS Portal. The World Elevation Cache service was created from: USGS GTOPO30 global coverage, USGS SRTM 90m coverage, USGS GMTED2010, and USGS California Central Coast Lidar.

[cid:image005.jpg@01D17FAF.0F5247F0] [cid:image006.jpg@01D17FAF.0F5247F0]

**Comment by elinz** [comment]
@dfoll What's the status of this issue? Thanks.

**Comment by Dbarnes1** [comment]
@dfoll - delete this service.

**Comment by dfoll** [comment]
i have taken personal ownership of this item and unshared it (instead of deleting, just in case, we find out we need it back for some reason, then it's still around for a couple days).

@ircampbell @kAilshie in the PA webmap i replaced this layer with the global elevation layer that @NatalieCampos recommends we use
