### ISSUE TITLE
LandCoverDemo image service cannot be added to ArcMap

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1414]
The LandCoverDemo image service is cannot be added to ArcMAP. See error below.  I could not find a cooresponding image service in the portal to test.  I am unsure what the error means.  I am unaware of whose service this is. Can you please assign to correct person? @elinz 

@jrweakland Is it necessary to have two land cover services? One for Demo and one for not?
![image](https://cloud.githubusercontent.com/assets/5116835/13796007/8a59f33a-eac1-11e5-8d37-30a36519211a.png)
l

**Comment by jrweakland** [comment]
@NatalieCampos - I do not believe that we need two services for the same data. My guess is that the LandCoverDemo image service is from last year's FedGIS and UC.

**Comment by NatalieCampos** [comment]
The description for this service is below.  As wells as the folder data on which it was created.  I also recommend deleting the service.  

![image](https://cloud.githubusercontent.com/assets/5116835/13797183/da04bbb6-eac8-11e5-8b55-504a5588da83.png)


![image](https://cloud.githubusercontent.com/assets/5116835/13797189/e5380510-eac8-11e5-9912-fd6b412c5e5a.png)

**Comment by elinz** [comment]
@NatalieCampos @jrweakland According to the portal service item, which does in fact exist (ccc51a902cd6495cb32692dafa8ea4c6), this service is owned by @dfoll. According to portal item description this service was for the storytelling workshop and should be deleted after the 22 may multispectral land characteristics consortium.

This service can't be accessed because the dataset this image service is based on doesn't exist:
(data server): Data\FoundationOverlays\LandCover\LandCoverDemo\LandCoverDemo.gdb\LandCoverDemo

@dfoll Can you please delete the NationalIntelligence\LandCoverDemo image service as according to portal item description it was supposed to have been deleted? You will also need to manually delete the associated portal item ccc51a902cd6495cb32692dafa8ea4c6. Thanks.

**Comment by ACueva** [comment]
I deleted the Image Service and Portal Item.

@dfoll Please verify and close issue.

**Comment by dfoll** [comment]
i don't see it in the REST endpoint anymore
