### ISSUE TITLE
Unable to publish to 3D webscene

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1416]
I am unable to publish a 3D point layer to a 3D scene.  The email is from Melanie Summers depicting the problem.  This issue is preventing the updating of the UMR template to Pro 1.3.

Hey Natalie,

So this succeeds when I share to our 10.4 portal but also fails for me going to "dev portal"

The error message the cache job is returning is ERROR 001812: Unable to connect to the database used for scene caches (ERROR: the server doesn't have a managed no-sql database.).

I double checked and you guys do have ArcGIS Data Store set as your managed database so I’m not sure why server thinks it isn’t there…

Melanie

**Comment by NatalieCampos** [comment]
3d multipatches fail to cache as well.

**Comment by elinz** [comment]
The problem was that the registration of the nosql database was corrupt, i.e through the Server admin API, we could not access the admin/data/items/nosqlDatabases/AGSDataStore_nnnnn/ machines/"machine" REST endpoint. After unregistering and re-registering ArcGIS Data Store the endpoint could be reached and validated. Web scene cache generation now works. Closing issue.
