### ISSUE TITLE
Execute Query Url is broken- WMS service will not add to map

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/ops-server-config#1520]
The Execute Query item threw a "URL issue" from the QC scripts. The WMS service isn't adding to the map. @dfoll since this item is an output of predictive analysis web I'm assigning you to offer insight/guidance on how this should be addressed. 

Link to item: https://"portal"/arcgis/home/item.html?id=3f67a3ea9022445d969da5dc3a966127

**Comment by dfoll** [comment]
@elinz not sure i can explain this as eloquently as @kAilshie did for me, but essentially this map service is the one used to display the results of running a particular instance of the gp service, which gets an "id" associated with it.  this portal item sorta points to nothing. on top of that, the workflow of adding this service to a map manually is not something we intend a user to do

i personally don't know where this portal item came from, as it's from DemoIntelligence

**Comment by dfoll** [comment]
sorry for the nonsense blabber...
@elinz maybe this explanation directly from @kAilshie will make more sense...

**Comment by elinz** [comment]
To my knowledge the errors thrown on WMS Urls are not really issues.

-------- Original message --------
From: Daniel Barnes
Date:09/09/2016 1:22 PM (GMT-08:00)
To: Esri/ops-server-config
Subject: [Esri/ops-server-config] Execute Query Url is broken- WMS service will not add to map (#1520)


The Execute Query item threw a "URL issue" from the QC scripts. The WMS service isn't adding to the map. @dfoll<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dfoll&d=DQMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=2ZpT4vzBgD3Uq0Qu1_1lvg&m=ES76zGw3_cinq79F6E5RaDzTR6fEGIpwCZHPGsIteyA&s=n9gFqIMFzv79KucfJLfFAhqusrdMTJm0AKy9oIi3MTQ&e=> since this item is an output of predictive analysis web I'm assigning you to offer insight/guidance on how this should be addressed.

Link to item: https://nsec.esri.com/arcgis/home/item.html?id=3f67a3ea9022445d969da5dc3a966127

-

**Comment by dfoll** [comment]
@elinz ... sounds like we can close this then?

**Comment by elinz** [comment]
@dfoll I'm going to delete the portal item 3f67a3ea9022445d969da5dc3a966127 since the map service json doesn't references any portal items so it's not necessary to have any portal items for this. I'm also going to delete the map service item b741ffa9eb41415daf4cff1023491be1 since it's not needed.

**Comment by elinz** [comment]
@dfoll Deleted these two portal items. Closing this issue.
