### ISSUE TITLE
Will "ProductsGallery" web app be released?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1546]
@CraigCleveland  Will the web app SolutionsWeb\Apps\NationalIntel\ProductsGallery be released? The associated portal item is owned by you. If it's not going to be released that please remove this app folder from the SolutionsWeb\Apps\NationalIntel so it's not shipped with the release. Alternatively, I can remove to another location on the server so it's not included, but you'll have a backup of this files. Thank you.

**Comment by elinz** [comment]
@CraigCleveland Moved this ProductsGallery app out of the SolutionsWeb\Apps\NationalIntel to the folder c:\EricL\TEM2016Release\SolutionsWeb_files_removed_from_release\Apps\NationalIntel\ProductsGallery on the server, so if you need it back let me know.

**Comment by CraigCleveland** [comment]
@elinz there was never any intention of this app making it into the Ops Server release.  I created the app for Tom Oaks/Phil Suarez/Daniel Maso & Co. for this years DIET.  Since the requirement was to use the NSEC Portal and the Ops Server that's where it ended up.  So long story short that's totally fine what you've done with it.

**Comment by elinz** [comment]
@CraigCleveland Thanks for the info Craig.
