### ISSUE TITLE
Error: Maritime Threat Tools web app doesnt function

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1578]
The following portal item (id=1a1fc46c72b24f49be0337316ce526ac) doesnt seem to function properly.

**Comment by elinz** [comment]
@NatalieCampos Please describe what doesn't function properly.

**Comment by NatalieCampos** [comment]
When i click on the widget, everything including the basemap disappears and leave me with just a dot.  Unsure how to use or test this widget.

![image](https://cloud.githubusercontent.com/assets/5116835/18728215/32ffbcca-8001-11e6-9b95-619546bc4407.png)

**Comment by ACueva** [comment]
@NatalieCampos That button you pushed is to give you your current location.  There is no imagery for Redlands.  It's expected behaviour.  I too don't know what this application does as there appear to be no widgets for it.  I believe the correct application is this one: 3d9dfacc976d43668428af44984bdc5e
