### ISSUE TITLE
Change Detection Relative Atmosphereic Correction 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#708]
There are tools in the Change detection toolbox that are pathed to the project and not pathed to the Change detection toolbox on Github.  Tools in the project toolbox should be removed/deleted and a step added to added the change detection toolbox from github.

**Comment by helyx-amcmillan** [comment]
We already tried three versions of the project where we pulled down tools from Github and this didn't work because of this issue with referencing the paths (even after recent updates). Hence I was advised to package the tools within the project. This traditionally didn't work either until I embedded the scripts within the tools. This seemed to work and other machines could open and load the tools from the project package. However there is still a path somewhere that is pointing back to Github. Have potentially sorted this, will try again today on Natalie's machine.

**Comment by NatalieCampos** [comment]
Tool are all found in the project folder. Not all of them work but at least there is only one set of the.
