### ISSUE TITLE
Release Farthest On Circle GP Service

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#722]
Recommend you release the Farthest On Circle GP service on the Ops Server (currently owned by @jfrygeo . This is a nice one to show dynamically, in WAB, etc.

**Comment by jfrygeo** [comment]
Agreed. Will proceed to publish on new geography servers post FedGIS

**Comment by jrweakland** [comment]
Added to backlog: https://app.asana.com/0/23169951437136/31304190918332

**Comment by jfrygeo** [comment]
Workaround for issue #777, - instead of using an image service as mask to power the tool, the mask was copied to the server, when the service was published. 

Farthest On Circle published top NSEC. https://nsec.esri.com/arcgis/home/item.html?id=779c8029eac24a129ce95a8f4caa8301

@jrweakland - please review for release.

**Comment by jrweakland** [comment]
We will not be releasing a workaround GP service from the NSEC Portal. @jfrygeo - please remove the workaround GP service and associated data on the NSEC Portal. I will review and release the proper GP service and associated data once you and @elinz have it running.

**Comment by jfrygeo** [comment]
Do we want the underlying data to be data in a geodatabase on the server, or data as an image service? Since it's on the server and will be copied when we cut the server, does it make a difference?

**Comment by elinz** [comment]
@jfrygeo Just because the data is copied to an Ops Server doesn't mean that the gp service would work with the data copied to the server. Having the gp service configured to work against an image service does work (it's just not working on our dev server). I have already tested on the trial UC server and the farthest on circle gp service appears to work the one using the data reference through an image service and not referenced through an image service.

**Comment by jfrygeo** [comment]
-Not able to release farthest on circle using an image service as background data for the tool to work. This is due to issue #777 .
![farthestoncredentials](https://cloud.githubusercontent.com/assets/5074686/9763030/45d80628-56d5-11e5-8c32-68178912adf1.PNG)

However, it can be released with using a raster in a file geodatabase but it is not optimal due to it being a workaround.

**Comment by jrweakland** [comment]
@jfrygeo - have you had a chance to speak to the raster team yet?

**Comment by jfrygeo** [comment]
I tried publishing about 1 month ago and still had same issue. Sorry I didn't have a chance to talk to raster and portal teams. Looks like in the github issue, Eric was trying to contact the team but a solution wasn't found.

Regards,
John
Sent from my iPhone

On Sep 20, 2015, at 2:22 PM, Jim Weakland <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://github.com/jfrygeo> - have you had a chance to speak to the raster team yet?

**Comment by jfrygeo** [comment]
tried again (today) to use farthest on circle using image service in a web application, but same errors occurred.

**Comment by elinz** [comment]
nothing has changed in terms of the server/portal configuration so same errors are expected.

**Comment by conklinbd** [comment]
So did we follow the workaround on the server (including the data in the publishing process)?

**Comment by conklinbd** [comment]
Based on my conversation with @elinz we will publish the service as is. It is a known issue that the service does not work on an IWA machine. The service will work if using built-in Portal authentication. There is nothing to resolve with this item for this release.

**Comment by jfrygeo** [comment]
republish farthest on circle image service gp tool to military folder?

Sent from my iPhone

On Sep 30, 2015, at 10:58 AM, Ben Conklin <notifications@github.com<mailto:notifications@github.com>> wrote:


So did we follow the workaround on the server (including the data in the publishing process)?

**Comment by jfrygeo** [comment]
Republished to military folder here: https://nsec.esri.com/arcgis/home/item.html?id=688999e1df1a4b3ca1eaa63996d3b487
