### ISSUE TITLE
What are the possible values for /CertType

### ISSUE THREAD

**Issue by VytautasGipiskis** [Esri/ops-server-config#735]
Please update the documentation with a list of possible values for /CertType (Page 14, 
C:\ops-server-config\Install\OpsDashboardUtility\CreateOneClickInstaller.bat)   If certificate is not a selfsigned, what value I should use for ?

**Comment by conklinbd** [comment]
@elinz Is there core documentation for this you can just point them to?

**Comment by elinz** [comment]
@VytautasGipiskis Upon further investigation, I've found that the /CertType parameter is actually ignored by the OperationsDashboardUtility.exe. If you're using a CA cert or domain cert you would use the /certpath parameter to specify the path to the cert and use the /password parameter to specify the cert password, otherwise your using a self-signed cert and don't need to use the /certpath or /password parameters as self-signed is assumed. 

I will be removing the /CertType parameter; see #758.

**Comment by VytautasGipiskis** [comment]
Thanks, you can close the issue.
