### ISSUE TITLE
Install doc - Desktop should not be installed

### ISSUE THREAD

**Issue by VytautasGipiskis** [Esri/ops-server-config#736]
Install doc (page 7 ) does not says nothing if ArcGIS Desktop needs to be uninstalled. If it is not, user will get an error because of PostgreSQL Libraries is not present.  Please update the doc.

**Comment by conklinbd** [comment]
@VytautasGipiskis when are you encountering this error? Desktop does not need to be installed on the server in order to run through the install. Please give some more information on when you are encountering this error.

**Comment by csmoore** [comment]
The ["Ops Server Installation Guide"](https://github.com/Esri/ops-server-config/tree/master/Docs) "Prepare for Ops Server Installation" does tell you to install Desktop (it was the last bullet - but I moved it up to the first in my Pull Request to try to make it more clear).

But I don't think the 2 installs (PostgreSQL and Desktop) are related so something else might be going on (like the PostgreSQL step might have been failing for another reason -or- this is a pre-10.3 version).  Previous (to 10.3) ArcGIS installs did require you to copy the postgres client libraries to the ArcGIS bin folder, but I don't think [that is the case now](http://desktop.arcgis.com/en/desktop/latest/manage-data/gdbs-in-postgresql/database-requirements-postgresql.htm).

**Comment by elinz** [comment]
ArcGIS Desktop is not required to install Ops Server. It's mentioned in the service publishing section of the "Ops Server Installation Guide" in cases where you need to republish a service from the original source and in this case you should install ArcGIS Desktop on a separate machine. (NOTE: installing desktop on the server machine changes the .py file association to point from the 64 bit Python installed with Server to the 32 bit Python installed with Desktop).

For ArcGIS Server (pre-10.3) to connect to PostgreSQL geodatabases it does require the PostgreSQL 64 bit client libraries (a separate install) to be installed to the C:\Program Files\ArcGIS\Server\bin folder. For ArcGIS Server 10.3, support to connect to PostgreSQL geodatabases is provided out of the box in order to support ArcGIS Data Store so you don't need to copy any files to the server bin folder.

The current ops server config scripts are for current build of ArcGIS (i.e. 10.3), so the InstallArcGISServer.bat no longer includes the copy statement to copy the pre-extracted PostgreSQL client library files.

**Comment by VytautasGipiskis** [comment]
Sorry to join discussion so late. 
I think issue was caused by background GP (not sure, if final version is installing python libraries).

**Comment by jrweakland** [comment]
@VytautasGipiskis - please verify and close if appropriate.
