### ISSUE TITLE
Crowd Source apps use external JS API references

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#748]
The Crowd Source apps currently use external JS Api references.
These are located in the index.html for these apps. The apps use jsapi 3.13 so I am not certain if they will work with Portal 10.31. I am not sure which version of the jsapi is installed. 

Also, jquery is being referenced. We may need to host jquery on the portal to get this to work offline.

**Comment by conklinbd** [comment]
@ACueva can you find out what version of the jsapi is on the portal?

**Comment by ACueva** [comment]
@conklinbd Yes.

**Comment by ACueva** [comment]
Portal 10.3.1 uses version 3.13 of the JSAPI.

This information can be found in the JSAPI kernel.js – see example below.

https://PORTAL/arcgis/jsapi/jsapi/esri/kernel.js

// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/kernel",["dojo/_base/kernel","dojo/_base/config","dojo/has"],function(c,d,e){var b=window.location,a=b.pathname,a={version:"3.13",_appBaseUrl:b.protocol+"//"+b.host+a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-1]))};d.noGlobals||(window.esri=a);c.isAsync||e.add("extend-esri",1);(a.dijit=a.dijit||{})._arcgisUrl=("file:"===b.protocol?"http:":b.protocol)+"//www.arcgis.com/sharing/rest";return a});

**Comment by conklinbd** [comment]
In reviewing it the jquery components are bundled with the app already so I only need to deal with the ArcGIS Javascript API urls.

**Comment by conklinbd** [comment]
Replaced 
//js.arcgis.com/3.12/dijit/themes/claro/claro.css with /arcgis/jsapi/jsapicompact/dijit/themes/claro/claro.css

//js.arcgis.com/3.12/esri/css/esri.css with /arcgis/jsapi/jsapicompact/esri/css/esri.css

//js.arcgis.com/3.12 with /arcgis/jsapi/jsapicompact/

**Comment by conklinbd** [comment]
@ACueva could you test this fix. This item uses the app id:29013195a6aa480c8bc3d1c34dbea5f0.
Note that the are error messages in the debug console but these existed before the change and the app appears to function correctly.

**Comment by ACueva** [comment]
Appears to be fixed.  I saw the other errors you were referring to, as noted, they do not appear to affect functionality. Marking resolved.
