### ISSUE TITLE
NSEC Portal Operations Dashboard Addins aren't valid.

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#757]
I get this error whenever I try to use these addins (every one is affected):

![image](https://cloud.githubusercontent.com/assets/5016557/7259369/9a68ae72-e817-11e4-81c6-ed738b06beae.png)

Latest version of the addins and latest version of Operations Dashboard.

**Comment by conklinbd** [comment]
I can not reproduce this issue. I installed Operations Dasbhoard from the NSEC server and then added the Bomb Threat AddIn and it added fine and worked. 
Please ensure that you are using the Operations Dashboard from the NSEC portal.

**Comment by elinz** [comment]
NOTE: when I upgraded the NSEC portal to 10.3.1, I also configured it with a newer Ops Dashboard build (Jan 2015) so if you _had_ installed Ops Dashboard from NSEC previously, it's best to install again to get the latest build.

**Comment by joebayles** [comment]
It works now that I uninstalled Operations Dashboard and reinstalled from the portal.

Weird thing is I had installed it from NSEC before, and I reinstalled it when I tried to open the Operations Dashboard from the portal on Monday. Might be a good thing to point out to folks later on.

**Comment by pHill5136** [comment]
Yeah I just got OOB up yesterday without too much of a problem. I created a throw away service service in the Test folder and a webmap with with units and equipment for testing OOB. I also created a feature class in the Military gdb. The schema for the feature Units and Land Equipment feature classes will work with the Dictionary renderer but also can be used for services, too. I just copied the schema from VCP. I had to add the field owningunit to the Land Equipment schema to capture that for OOB widget. We may want to delete the features I created, but I think we can keep the feature classes for when we build out unit equipment data on nsec.

One other caveat with OOB widget is that the feature services feeding the OOB must be using a unique value renderer (for the layers feeding the widget) - which would be the default for equipment or units, but there is an error if a layer does not use unique values - I was using a single value renderer to start and saw the error. I think this was by design and has something to do with being able to grab the image used for military symbols so they can be displayed in the widget.
