### ISSUE TITLE
Should the Miltary/MissionReport_201505190930 service be deleted?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#772]
Based on the fact that the service name has a time stamp appended and the service is in a stopped state, I believe that the publisher attempted to delete/overwrite the service "MissionReport", but the deletion process did not successfully complete.

**Comment by phil7277** [comment]
Eric,
I was trying to overwrite the service, because it was not working. The first error stated this feature service was not editable.


Regards,
Phil

Phil Suarez | Solutions
Esri | Defense & Intelligence
8615 Westwood Center Dr. | Vienna, VA. 22180 | USA
T 909-793-2853<tel:909-793-2853> x2829 | M 571-328-6802<tel:571-328-6802>
psuarez@esri.com<mailto:psuarez@esri.com> | www.esri.com<http://www.esri.com/>

**Comment by elinz** [comment]
@phil7277 @jrweakland Closing issue as this service no longer exists.
