### ISSUE TITLE
Services do not adhere to NSEC team naming conventions

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#773]
- [ ] Military\MAOW_freshOpI.MapServer
- [ ] Military\MAOW_freshOpI2.MapServer
- [ ] Military\MAOW_Weather_OpImpact.MapServer
- [ ] Military\MAOWTemplate_publish_Just_Weather.MapServer
- [ ] Military\Op_Impact_Air_Cloud_Ceiling.MapServer
- [ ] Military\Op_Impact_Air_Temperature.MapServer
- [ ] Military\Op_Impact_Air_Visibility.MapServer
- [ ] Military\Op_Impact_Bridge_Crossing_Wind.MapServer
- [ ] Military\Op_Impact_Windspeed.MapServer

**Comment by jrweakland** [comment]
This issue was moved to ArcGIS/mil-intel-desktop-solutions-templates#72

**Comment by jrweakland** [comment]
@elinz -  You are correct, these services do not adhere to the naming convention. I am moving this issue to the https://github.com/ArcGIS/mil-intel-desktop-solutions-templates repo to be managed since the services are a derivative from the MAoW v2.0.0 template.

@abrowning80 - This will need to be addressed in the naming convention of the layers from the MAoW v2.0.0 template.
