### ISSUE TITLE
unable to publish 3d multipatches as web layer

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#837]
I am unable to publish 3d multipatches as a web layer in on the NSEC portal.  I should be able to publish 3d layers to any 10.3.1 portal.  I can publish the same 3d layer to another 10.3.1 portal.  

Good portal
![image](https://cloud.githubusercontent.com/assets/5116835/8490060/f11219a4-20d7-11e5-8eb6-80b71f1c3431.png)
Bad portal
![image](https://cloud.githubusercontent.com/assets/5116835/8490074/0c25eef0-20d8-11e5-8a12-2b343c249dc8.png)

**Comment by conklinbd** [comment]
@NatalieCampos this might be the same issue that @craigcleveland ran into if he was signed in to more than 1 portal. Might be worth checking with him to see if he resolved it.

**Comment by NatalieCampos** [comment]
I will check with him but I don't think it is the same issue as I was only signed into 1 portal when I ran into the problem.  I was able to sign into a dev portal and publish while still being connect to nsec but I just can't publish from nsec.  I did run through testing with the 3d team to try to isolate the problem.  We think it is a portal configuration problem or a permissions problem.  I don't know.

**Comment by CraigCleveland** [comment]
The issue is similar, but I don't think it's the same.  I also couldn't publish a multipatch as a web layer, but the reason for the issue I was facing is I could not get signed into a particular Portal.  Once I was able to get signed in I could publish.  My challenge has been that intermittently I'm unable to get signed into Portals for some reason (which subsequently presents the same challenge Natalie is facing).

**Comment by NatalieCampos** [comment]
@elinz I am able to publish 3d polygon layers to the UC trial Ops Server using the same data that failed for the NSEC server.  I am unsure what the difference between servers is.

https://nsecmini07.esri.com/arcgis/home

**Comment by CraigCleveland** [comment]
@elinz Any update on this issue?  I'm finding the identical experience to @NatalieCampos - I'm able to successfully publish polygon multipatch feature classes (e.g. buildings) to other Portals, including my own and UC related NSEC Portals (e.g. nsecmini04), but not the "master" NSEC Portal.

**Comment by elinz** [comment]
@CraigCleveland Can you provide me data so I can reproduce? Thanks.

**Comment by CraigCleveland** [comment]
@elinz I've sent some sample buildings for you to work with via email.  The file size was too big to attach here.

**Comment by elinz** [comment]
@CraigCleveland What are the steps to reproduce? What type of ArcGIS Pro project are you creating?

**Comment by CraigCleveland** [comment]
@elinz you can reproduce by opening ArcGIS Pro, creating a new Scene, adding the buildings I sent and then trying to Share as Web Layer.  I was able to move past the point @NatalieCampos was because @ACueva temporarily bumped up my account on NSEC, however nothing ever successfully published.

**Comment by elinz** [comment]
@CraigCleveland Thanks. I'll have to look at this another time. Right now I can't publish any hosted service to the portal from ArcGIS Pro or ArcMap.

**Comment by elinz** [comment]
@CraigCleveland I created a local scene project in ArcGIS Pro, added the buildings you provided, but on the Share ribbon there is no Share as "Web Layer" icon. There is only a Share As "Web Scene" and it's disabled.

**Comment by CraigCleveland** [comment]
@elinz that was the initial experience @NatalieCampos had, as well as I had, but I was able to move beyond that when @ACueva bumped me up to Admin temporarily.  Not that that should have anything to do with it, but that's what worked to at least enable the button...however publishing continued to fail.

**Comment by elinz** [comment]
@CraigCleveland my account is an administrator.

**Comment by NatalieCampos** [comment]
@elinz This is what needs to happen

1.  you have to be logged into a portal account
2.  you need to have your buildings as a 3d layer. Use the *Layer 3D to Feature Class* to create the 3D layer.  
3. You can share your buildings as a 3D layer so that they can be added to a portal scene by right clicking and sharing as a web layer. 
![image](https://cloud.githubusercontent.com/assets/5116835/8915964/1f3c54aa-345d-11e5-875f-41213bc23beb.png)

4. Or you can share the web scene.  
![image](https://cloud.githubusercontent.com/assets/5116835/8915980/3a33c45a-345d-11e5-9ac5-2d6c7ce94088.png)


The main issue is that when published to other portals the exact same builidngs are successfully published and rendered in scene.  In our NSEC portal they are not rendered all other layers are rendered however.  I have shared my data with the 3D content team prior to UC and it was determined that there was no issue with the data I was using as the data was successfully published to two other portals.  The 3D team said it had to be our portal.  Bummer

**Comment by CraigCleveland** [comment]
@elinz any update on the status of this?

**Comment by elinz** [comment]
@CraigCleveland Found that the custom role for "Publish hosted scene layers" was disabled. I've enabled the role for all customer roles that allow users to publish hosted content. @NatalieCampos is going to re-test in the morning. I've tested and as a non-administrator I was able to publish the buildings you provide me successfully as a web scene. I could then view the buildings in scene viewer once the cache job was finished. Won't close until you can verify the fix.

**Comment by CraigCleveland** [comment]
@elinz that's great news!  I just ran a quick test with no luck, but I am on VPN now and have mix luck with NSEC while off the network.  I'll try it again in the AM and let you know how I make out.

**Comment by CraigCleveland** [comment]
@elinz I tried to publish buildings again this morning and was met with failure, but after re-reading your note above I think it may have to do with my role.  At the moment I'm listed as an Administrator (a remnant of troubleshooting pre-UC with Avi I believe), and you noted your update was to all "customer" roles and that you used a non-Admin role in your testing.  Due to that maybe a downgrade of my role is required?  I can't imagine why an Administrator couldn't publish Scene Services, but maybe you tweaked that role?  Anyway let's try moving me back to a standard role for an SE and see if we can find success.  Thanks.

**Comment by elinz** [comment]
Administrators can publish web scene layers. My user as an admin can publish and I tested changing my role to a custom role such as solutions team member and can publish no problems and the buildings draw once the caching job has finished.

-------- Original message --------
From: Craig Cleveland
Date:09/01/2015 5:23 AM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: Re: [ops-server-config] unable to publish 3d multipatches as web layer (#837)


@elinz<https://github.com/elinz> I tried to publish buildings again this morning and was met with failure, but after re-reading your note above I think it may have to do with my role. At the moment I'm listed as an Administrator (a remnant of troubleshooting pre-UC with Avi I believe), and you noted your update was to all "customer" roles and that you used a non-Admin role in your testing. Due to that maybe a downgrade of my role is required? I can't imagine why an Administrator couldn't publish Scene Services, but maybe you tweaked that role? Anyway let's try moving me back to a standard role for an SE and see if we can find success. Thanks.

**Comment by elinz** [comment]
@CraigCleveland did more testing. I can publish a web scene and the buildings successfully display (after caching), but I when I publish the buildings layer in ArcGIS Pro as a web layer and then try to the web layer in Scene Viewer I receive an error stating "Layer cannot be added: Multipatch Feature Services are not supported.

**Comment by elinz** [comment]
@CraigCleveland Published the buildings as a web layer to another 10.3.1 portal/server and the building feature service does add to Scene viewer and does draw. Hmmm?

**Comment by CraigCleveland** [comment]
@elinz that's been my experience all along...  Not sure what's happening with NSEC Portal???

**Comment by elinz** [comment]
@CraigCleveland @NatalieCampos When you publish the web layer, both a feature layer item and scene layer item are created in the portal. When adding to scene viewer you have to add the scene layer not the feature layer (even though "Add layer to scene" is in the context drop down control). Adding a feature layer to scene only works if the underlying feature service is not multipatch.

**Comment by CraigCleveland** [comment]
@elinz I'm cooking with gas now.  I am able to successfully publish Scene Services with multipatch features!  The bottom line is it takes awhile on NSEC for the building cache to be built, but after that completes it's good to go.

**Comment by elinz** [comment]
Resolution summary:
1) Non-administrators could not publish web scenes or web layers because the "Publish hosted scene layers" role was not enabled. Enabled for all custom roles where we allow users to create hosted type of content.
2) The data won't display in the Scene Viewer until the cache has completed building. The caching process took awhile on the dev server so unless you checked on the caching job to make sure it complete you would believe the publishing process failed somewhere in the process.
3) Although the "Add layer to scene" context option is available on feature layer items, this only works if the underlying feature service isn't multipatch. Instead of adding the feature layer to the scene viewer you must add the scene layer that is created when you publish the service.
