### ISSUE TITLE
Web Map "Maritime Domain Awareness Dashboard" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#874]
Item id 995d354c59694c01bbd1ff877441526a references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/ProximityAlert/FeatureServer/0

Examine the rest endpoint for this service and you will find that the layer number is 47 not 0.
https://nsec.esri.com/ags/rest/services/Military/ProximityAlert/FeatureServer

**Comment by jfrygeo** [comment]
@elinz @pHill5136 This issue came up when I was required to "Allow assignment of unique numeric IDs for map service publishing." When overwriting services, it broke the web map by breaking references to the previous feature services. I had to manually create the web map again, update the Operations Dashboard, and fix all geofences, geoevent services, and outputs in GeoEvent Processor. The dashboard should be up and running.

**Comment by pHill5136** [comment]
The problem with the geoevent manager has been fixed by a new patch which I applied a little while ago. It will recognize both standard layer indexes and unique layer indexes.

It should be noted that the patch is implemented manually on our instance of gee. Out of the box 10.3.1 will only recognize standard layer indexes.

The problem with webmaps being corrupted after republishing using a new indexing method, I think is a significant bug that would need to be repaired by the agol / portal dev team.

**Comment by conklinbd** [comment]
That is a known issue/as designed in the web map. This is why we should always use Unique IDs from the beginning, otherwise any change in map layer order or grouping will break web maps and dashboards.

If you use unique ids (immutable) then you do not ever have this issue.
