### ISSUE TITLE
Need geoevent services for sustainment

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#907]
@abrowning80 @helyx-rterry @joebayles 

We need to get geoevent services and valid service definitions with the exact name of the <_type> tag for geoevent definitions coming into the geomessage adapter. Any fields that don't match on the incoming definition will be dropped by the geomessage input connector.

**Comment by abrowning80** [comment]
Looking into this in the next 24 hrs.

**Comment by conklinbd** [comment]
@pHill5136, @joebayles, @jrweakland @abrowning80 @helyx-rterry 

As I discussed with @abrowning80 today this is a nice to have, not a must have.
This is a major project that should have been planned properly and not just tried to shoe horn in at the last minute.

If you guys can do this, I hope you realize that you need to do it on multiple servers since the content has already been copied.
We will not be delaying the shutdown of the Servers on Thursday if this is not complete.

**Comment by pHill5136** [comment]
@abrowning80 @joebayles @jrweakland 

The sustainment services are still up on https://afmieopsgep.esri.com:6143/geoevent/manager.

You can use this to model the sustainment services. The login pw are the same as elsewhere.

Note that you may have to point the output services to different feature services.

**Comment by helyx-rterry** [comment]
To my knowledge there are some of the Sustainment services running on afmiedev but certainly the primary service is missing. There is probably enough on there to get you through a short demo. The output services could be pointed at the new Sustainment Reporting service on NSEC - presuming that that there is no issue with adding NSEC portal as a registered server to amfiedevgep GEE? If you are going to use afmiedev you could also use the new input messages that point to the new geography as they use the same data model and schema as the original. I will  do what I can from this end today

**Comment by helyx-rterry** [comment]
*afmieopsgep  is the server I was referring to sorry!

**Comment by abrowning80** [comment]
This is being worked on at present and a working version should be available soon.

**Comment by abrowning80** [comment]
@pHill5136 This was for UC which has now passed so can be closed.  A new version of the dashboard is being worked on and should be available soon.
