### ISSUE TITLE
Data Issues with World Elevation WGS84 Service

### ISSUE THREAD

**Issue by Nekillims** [Esri/ops-server-config#922]
Visual anomalies where high resolution data was added, query sometimes returns "missing" .  This could cause problems with appllications that use the elevation data.
![world elevation wgs84 screen](https://cloud.githubusercontent.com/assets/11337235/8994366/d8bb36c6-36d8-11e5-88a4-d24842c35079.JPG)

**Comment by Nekillims** [comment]
Profile web app template points to ArcGIS Online elevation data and profile does not agree with elevation data viewed in map display.
![elevation profiles screen](https://cloud.githubusercontent.com/assets/11337235/8994718/1d45ab4e-36db-11e5-9fba-dcd2f32fc3d0.JPG)
Need a version of the template that allows user to select elevation source.

**Comment by conklinbd** [comment]
@Nekillims this second comment seems to be unrelated and should be opened as a seperate issue.

**Comment by Nekillims** [comment]
Yes I just caught that.

**Comment by NatalieCampos** [comment]
A unit conversion was added to all the Lidar derived mosaic dataset items.  This fixes the visual anomalies.

![image](https://cloud.githubusercontent.com/assets/5116835/9042579/818728b2-39c4-11e5-9ca6-fccafe8ee522.png)

**Comment by Nekillims** [comment]
@NatalieCampos  Much better, but it looks like there is a missing "tile" at center right and a couple of other anomalies to the south, and one in Monterey Bay that stands out.  As an old-school DTED guy, these types of anomalies will generate questions about the data.   For our purposes, I'm not sure how much effort we should be spending on cleaning up the data.

**Comment by NatalieCampos** [comment]
The voids/anomalies are expected behavior.  This issue is that the extent of the lidar (in las file format) is based on geometry and a void fill applied.  This allows us to create a surface from points and fill in areas that are missing (houses, vegetation).  The void fill causes the triangulation to the geometry extent.  Seen below in the red lines.  The void fill prevents the mosaic dataset from using a lower resolution raster because it has been filled.  

![image](https://cloud.githubusercontent.com/assets/5116835/9236041/3c44d6de-40f7-11e5-9ef9-117446951c8e.png)


One option to get around this is to not use LAS points in the mosaic dataset but to go from LAS to a raster to a mosaic dataset.  In converting the LAS files to a raster we would be losing some of the spatial resolution of the LAS files.  Best practice is to use 3x point spacing so we would be reducing our spatial resolution by 3x, i.e. 1m lidar point cloud would result in a 3m raster.  We also would be slightly increasing performance as we would not be triangulating points on the fly.

**Comment by Nekillims** [comment]
I spoke with Gerry Kinn about this today since he is on the raster team.  We are thinking that there should be a way in the LAS to set the values of the missing points to null so that the mosaic dataset (or any other application using the LAS) will "know" not to include them in any calculation.  If this problem is typical of LAS datasets, it could be problematic for users doing terrain calculations that do not behave properly where there is missing data.  I will follow up to investigate further.  As I said earlier, we can probably live with these anomalies in our model geography, but our users need the capability to correct the problem of missing data.

**Comment by jrweakland** [comment]
@Nekillims - have you spoke to Clayton Crawford or Steve Snow about this issue?

**Comment by Nekillims** [comment]
@jrweakland  No, but Gerry and I went through it this morning.  There are editing tools that can be applied to the surface or elevation model derived from the LAS dataset to designate the area of missing data with a  "no data"  flag.  when ingested into the mosaic dataset, the system will ignore the areas of "no data" when processing and pick the next best dataset.
1.  LAS to surface or elevation model
2.  Set areas of missing data to "No Data"
3.  Ingest into MD and configure elevation services
We need to decide if this is worth doing for the model geography
