### ISSUE TITLE
Web map "Predictive Analysis Demo Map" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#998]
Web map "Predictive Analysis Demo Map" (id: e8effa285e7e4cfcab3b004a3cfc8e55) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromWaterSourcesMosaic/ImageServer

**Comment by kAilshie** [comment]
@elinz I created this web map just a few days ago and this service existed.  I checked with the content owner and he said he did not delete any items.  Do you know what happened to the service? I would like, if possible, to continue using it.

**Comment by elinz** [comment]
@kAilshie The service does not exist anymore, so someone deleted it.

**Comment by elinz** [comment]
@kAilshie The service was deleted this morning because the associated portal item did not exist. This meant that someone previously attempted to delete the service, but did not perform the delete correctly (i.e. for non-hosted services they must delete the service through the ArcGIS Server connection and not by deleting the portal item).

**Comment by kAilshie** [comment]
I had Ian republish the service.  I believe this issue has been resolved.

**Comment by conklinbd** [comment]
Process note: If you fix something then please assign back to the issue originator for verification and mention them in a comment.

**Comment by conklinbd** [comment]
@elinz for verification

**Comment by elinz** [comment]
Verified the issue has been fixed. Closing issue.

**Comment by csmoore** [comment]
@Esri/arcgis-defense-team - this is probably a good refresher/reminder for everyone (since we have occasionally gotten away from this):

Don't close the issue when you fix it (unless it is something trivial and/or you are the originator) - but assign it to be verified **by the issue originator** :

In the issue
1. Add a note about where you fixed this (commit#, URL, etc.) so it is clear where to get the fix
2. Change the label to "3 - Verify"
3. Assign back to the originator to verify (and add a comment assigning to `@originator` to verify)
4. That person should verify within a week (sooner if high priority) and then 1) close or 2) report that it is not fixed
5. If they don't verify, you can auto-close after a week (with a note that it wasn't verified)

See the OneNote "Github Issues" section if you want the entire, unabridged version of this, but we want to continue improving on this issue verification process (and when things are the busiest/most in flux is actually when this process seems to help the most).

**Comment by elinz** [comment]
@Esri/arcgis-defense-team Thanks @csmoore for reminding the team about the process.

**Comment by kAilshie** [comment]
I do not have the ability to change the assigner or add/change labels in this repo.

**Comment by conklinbd** [comment]
@kAilshie looks like you aren't part of the Defense team @csmoore should add you.

**Comment by csmoore** [comment]
@kAilshie - I added you so please try again (not sure how/why you were never added to our Esri team/org, but you should be there now)
